"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import EmployeeRecoveryPanel from "./EmployeeRecoveryPanel";

const emptyForm = { name: "", nationalId: "", personnelCode: "", bankAccount: "", department: "", jobGroup: "", role: "", email: "", companyId: "" };
const steps = ["هویتی", "شغلی", "بانکی", "دسترسی"];
const text = (v) => (v === null || v === undefined ? "" : String(v).trim());
function getExcelValue(row, keys) { for (const key of keys) if (row[key] !== undefined && row[key] !== null && text(row[key])) return text(row[key]); return ""; }

export default function EmployeesPage() {
  const [employees, setEmployees] = useState([]), [companies, setCompanies] = useState([]);
  const [activeCompanyId, setActiveCompanyId] = useState(""), [form, setForm] = useState(emptyForm);
  const [step, setStep] = useState(1), [search, setSearch] = useState(""), [loading, setLoading] = useState(true);
  const [loadingCompanies, setLoadingCompanies] = useState(true), [saving, setSaving] = useState(false), [importing, setImporting] = useState(false);
  const [editingId, setEditingId] = useState(null), [passwordEmployee, setPasswordEmployee] = useState(null), [recoveryEmployee, setRecoveryEmployee] = useState(null);
  const [newPassword, setNewPassword] = useState(""), [savingPassword, setSavingPassword] = useState(false);
  const [deleteEmployee, setDeleteEmployee] = useState(null), [deleteArmed, setDeleteArmed] = useState(false), [deleting, setDeleting] = useState(false), [toast, setToast] = useState(null);
  const fileRef = useRef(null);
  const activeCompany = useMemo(() => companies.find((c) => String(c.id) === String(activeCompanyId)), [companies, activeCompanyId]);
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); if (!q) return employees; return employees.filter((e) => [e.full_name,e.national_id,e.personnel_code,e.department,e.job_group,e.job_title,e.bank_account,e.email].some((v) => text(v).toLowerCase().includes(q))); }, [employees, search]);
  const withPassword = employees.filter((e) => Boolean(e.has_payslip_password || e.payslip_password)).length;
  function notify(message, type = "success") { setToast({ message, type }); window.setTimeout(() => setToast(null), 3200); }
  async function loadEmployees(companyId = activeCompanyId) { if (!companyId) { setEmployees([]); setLoading(false); return; } try { setLoading(true); const r = await fetch(`/api/personnel?company_id=${encodeURIComponent(companyId)}`, { cache: "no-store" }); const data = await r.json(); if (!data.success) throw new Error(data.error || "خطا در دریافت کارکنان"); setEmployees(Array.isArray(data.data) ? data.data : []); } catch (e) { console.error(e); notify(e.message || "خطا در اتصال به سرور", "error"); } finally { setLoading(false); } }
  async function loadCompanies() { try { setLoadingCompanies(true); const r = await fetch("/api/companies", { cache: "no-store" }), data = await r.json(); if (!data.success) throw new Error(data.error || "خطا در دریافت شرکت‌ها"); const list = Array.isArray(data.data) ? data.data : []; setCompanies(list); setActiveCompanyId((cur) => cur && list.some((c) => String(c.id) === String(cur)) ? cur : list[0] ? String(list[0].id) : ""); } catch (e) { console.error(e); notify(e.message, "error"); } finally { setLoadingCompanies(false); } }
  useEffect(() => { loadCompanies(); }, []);
  useEffect(() => { if (activeCompanyId) { setSearch(""); setForm((f) => ({ ...f, companyId: String(activeCompanyId) })); loadEmployees(activeCompanyId); } }, [activeCompanyId]);
  function resetForm() { setForm({ ...emptyForm, companyId: activeCompanyId }); setStep(1); setEditingId(null); }
  function editEmployee(e) { setForm({ name:text(e.full_name),nationalId:text(e.national_id),personnelCode:text(e.personnel_code),bankAccount:text(e.bank_account),department:text(e.department),jobGroup:text(e.job_group),role:text(e.job_title),email:text(e.email),companyId:String(e.company_id || activeCompanyId) }); setEditingId(e.id); setStep(1); window.scrollTo({ top:0, behavior:"smooth" }); }
  function validateStep(n) { if (n === 1 && (!form.name.trim() || !form.nationalId.trim() || !form.personnelCode.trim())) { notify("نام، کد ملی و کد پرسنلی الزامی هستند.","error"); return false; } if (n === 4 && form.email.trim() && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) { notify("فرمت ایمیل صحیح نیست.","error"); return false; } return true; }
  function nextStep() { if (validateStep(step)) setStep((s) => Math.min(4,s+1)); }
  async function submit(e) { e.preventDefault(); if (!activeCompanyId || !validateStep(1) || !validateStep(4)) return; try { setSaving(true); const editing = editingId !== null; const r = await fetch("/api/personnel", { method:editing?"PUT":"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ id:editingId,company_id:Number(activeCompanyId),full_name:form.name.trim(),national_id:form.nationalId.trim(),personnel_code:form.personnelCode.trim(),bank_account:form.bankAccount.trim(),department:form.department.trim(),job_group:form.jobGroup.trim(),job_title:form.role.trim(),email:form.email.trim().toLowerCase() || null }) }); const data=await r.json(); if(!r.ok||!data.success) throw new Error(data.error||"عملیات انجام نشد"); notify(editing?"اطلاعات کارمند ویرایش شد.":"کارمند جدید ثبت شد."); resetForm(); await loadEmployees(activeCompanyId); } catch(e) { console.error(e); notify(e.message||"خطا در ذخیره","error"); } finally { setSaving(false); } }
  async function setPassword() { if(!passwordEmployee)return; const p=newPassword.trim(); if(p.length<4)return notify("رمز عبور حداقل ۴ کاراکتر باشد.","error"); try { setSavingPassword(true); const r=await fetch("/api/personnel",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:passwordEmployee.id,company_id:Number(activeCompanyId),full_name:text(passwordEmployee.full_name),national_id:text(passwordEmployee.national_id),personnel_code:text(passwordEmployee.personnel_code),department:text(passwordEmployee.department),job_title:text(passwordEmployee.job_title),bank_account:text(passwordEmployee.bank_account),job_group:text(passwordEmployee.job_group),email:text(passwordEmployee.email)||null,payslip_password:p})}); const data=await r.json(); if(!r.ok||!data.success)throw new Error(data.error||"تعیین رمز انجام نشد"); setPasswordEmployee(null);setNewPassword("");notify("رمز ورود فیش حقوقی ذخیره شد.");await loadEmployees(activeCompanyId); } catch(e){console.error(e);notify(e.message,"error");}finally{setSavingPassword(false);} }
  async function deleteEmployeeNow(){if(!deleteEmployee||!deleteArmed)return;try{setDeleting(true);const r=await fetch("/api/personnel",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:deleteEmployee.id,company_id:Number(activeCompanyId)})});const data=await r.json();if(!r.ok||!data.success)throw new Error(data.error||"حذف انجام نشد");setDeleteEmployee(null);setDeleteArmed(false);notify("کارمند و اطلاعات حقوقی وابسته حذف شد.");await loadEmployees(activeCompanyId);}catch(e){console.error(e);notify(e.message,"error");}finally{setDeleting(false);}}
  async function importExcel(event){const file=event.target.files?.[0];if(!file||!activeCompanyId)return;try{setImporting(true);const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=wb.SheetNames[0];const rows=sheet?XLSX.utils.sheet_to_json(wb.Sheets[sheet],{defval:""}):[];const items=rows.map((row)=>({full_name:getExcelValue(row,["نام و نام خانوادگی","نام","full_name"]),national_id:getExcelValue(row,["کد ملی","کدملی","national_id"]),personnel_code:getExcelValue(row,["کد پرسنلی","کدپرسنلی","personnel_code"]),bank_account:getExcelValue(row,["شماره حساب","حساب بانکی","bank_account"]),department:getExcelValue(row,["واحد","واحد سازمانی","department"]),job_group:getExcelValue(row,["گروه شغلی","گروه","job_group"]),job_title:getExcelValue(row,["عنوان شغلی","سمت","job_title"]),email:getExcelValue(row,["ایمیل","email","Email"])})).filter((x)=>x.full_name&&x.national_id&&x.personnel_code);if(!items.length)throw new Error("هیچ ردیف معتبری پیدا نشد.");if(!window.confirm(`${items.length.toLocaleString("fa-IR")} ردیف برای «${activeCompany?.name||"شرکت فعال"}» آماده ثبت است.\n\nادامه می‌دهید؟`))return;let ok=0,bad=0;for(const item of items){try{const r=await fetch("/api/personnel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...item,company_id:Number(activeCompanyId)})});const d=await r.json();if(r.ok&&d.success)ok++;else bad++;}catch{bad++;}}await loadEmployees(activeCompanyId);notify(`ورود Excel: ${ok.toLocaleString("fa-IR")} موفق، ${bad.toLocaleString("fa-IR")} ناموفق.`);}catch(e){console.error(e);notify(e.message||"خطا در خواندن Excel","error");}finally{setImporting(false);if(fileRef.current)fileRef.current.value="";}}
  function downloadTemplate(){const ws=XLSX.utils.json_to_sheet([{ "نام و نام خانوادگی":"علی رضایی","کد ملی":"0012345678","کد پرسنلی":"1001","شماره حساب":"6037991234567890","واحد":"مالی","گروه شغلی":"کارشناس","عنوان شغلی":"کارشناس مالی","ایمیل":"employee@example.com" }]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"کارکنان");XLSX.writeFile(wb,"template-employees.xlsx");}
  const field=(label,key,placeholder,type="text")=><label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><input type={type} value={form[key]} onChange={(e)=>setForm((f)=>({...f,[key]:e.target.value}))} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-3 text-sm outline-none focus:border-indigo-500 focus:bg-white focus:ring-4 focus:ring-indigo-100" placeholder={placeholder}/></label>;
  return <main dir="rtl" className="min-h-screen bg-slate-100 px-3 py-4 text-slate-800 sm:px-5 lg:px-8">
    {toast&&<div className={`fixed inset-x-3 top-3 z-[100] mx-auto max-w-md rounded-2xl px-4 py-3 text-sm font-bold shadow-2xl ${toast.type==="error"?"bg-rose-600 text-white":"bg-emerald-600 text-white"}`}>{toast.message}</div>}
    <div className="mx-auto max-w-[1600px]">
      <section className="mb-4 overflow-hidden rounded-3xl bg-gradient-to-l from-indigo-700 via-indigo-600 to-violet-600 p-4 text-white shadow-xl sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-1 text-xs font-bold text-indigo-100">سیستم حقوق و دستمزد</div><h1 className="text-2xl font-black tracking-tight sm:text-3xl">مدیریت کارکنان</h1><p className="mt-1 text-xs leading-6 text-indigo-100 sm:text-sm">همه عملیات این صفحه فقط روی شرکت فعال انجام می‌شود.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="کل کارکنان" value={employees.length}/><Stat label="دارای رمز" value={withPassword}/><Stat label="بدون رمز" value={employees.length-withPassword}/><Stat label="نتیجه جستجو" value={filtered.length}/></div></div></section>
      <section className="sticky top-2 z-30 mb-4 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur sm:p-4"><div className="grid gap-3 lg:grid-cols-[minmax(240px,360px)_1fr_auto_auto] lg:items-end"><label className="block"><span className="mb-1.5 block text-xs font-black text-slate-600">شرکت فعال</span><select value={activeCompanyId} onChange={(e)=>{resetForm();setActiveCompanyId(e.target.value)}} disabled={loadingCompanies} className="w-full rounded-xl border border-indigo-200 bg-indigo-50 px-3.5 py-3 text-sm font-black text-indigo-900"><option value="">انتخاب شرکت...</option>{companies.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="relative block"><span className="mb-1.5 block text-xs font-black text-slate-600">جستجوی سریع</span><input value={search} onChange={(e)=>setSearch(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-10 py-3 text-sm outline-none focus:border-indigo-500 focus:bg-white" placeholder="نام، کد ملی، کد پرسنلی، واحد، سمت، ایمیل..."/></label><button type="button" onClick={()=>fileRef.current?.click()} disabled={!activeCompanyId||importing} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{importing?"در حال ورود...":"ورود Excel"}</button><button type="button" onClick={downloadTemplate} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-black">قالب Excel</button><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={importExcel}/></div>{activeCompany&&<div className="mt-3 text-xs font-bold text-slate-500"><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-indigo-700">شرکت: {activeCompany.name}</span></div>}</section>
      <div className="grid gap-4 xl:grid-cols-[390px_minmax(0,1fr)]">
        <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5 xl:sticky xl:top-24 xl:self-start"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-black">{editingId?"ویرایش کارمند":"افزودن کارمند"}</h2><p className="mt-1 text-xs text-slate-500">فرم مرحله‌ای حرفه‌ای</p></div>{editingId&&<button type="button" onClick={resetForm} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-black">انصراف</button>}</div><div className="mb-5 grid grid-cols-4 gap-1.5">{steps.map((s,i)=><button key={s} type="button" onClick={()=>i+1<=step&&setStep(i+1)} className={`rounded-xl px-2 py-2 text-[11px] font-black ${step===i+1?"bg-indigo-600 text-white":i+1<step?"bg-indigo-50 text-indigo-700":"bg-slate-100 text-slate-400"}`}><span className="block text-base">{i+1}</span>{s}</button>)}</div><form onSubmit={submit}>{step===1&&<div className="space-y-3">{field("نام و نام خانوادگی *","name","مثلاً علی رضایی")}{field("کد ملی *","nationalId","۱۰ رقمی")}{field("کد پرسنلی *","personnelCode","مثلاً 1001")}</div>}{step===2&&<div className="space-y-3">{field("واحد سازمانی","department","مثلاً مالی")}{field("گروه شغلی","jobGroup","مثلاً کارشناس")}{field("عنوان شغلی","role","مثلاً کارشناس مالی")}</div>}{step===3&&<div className="space-y-3">{field("شماره حساب","bankAccount","شماره حساب یا شبا")}</div>}{step===4&&<div className="space-y-3"><div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-xs leading-6 text-indigo-800"><div className="font-black">🔐 دسترسی و بازیابی رمز</div><div className="mt-1">ایمیل برای بازیابی امن رمز استفاده می‌شود.</div></div>{field("📧 ایمیل پرسنل","email","employee@example.com","email")}</div>}<div className="mt-5 flex gap-2">{step>1&&<button type="button" onClick={()=>setStep((s)=>s-1)} className="flex-1 rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-black">قبلی</button>}{step<4?<button type="button" onClick={nextStep} className="flex-1 rounded-xl bg-indigo-600 px-3 py-3 text-sm font-black text-white">مرحله بعد</button>:<button type="submit" disabled={saving||!activeCompanyId} className="flex-1 rounded-xl bg-emerald-600 px-3 py-3 text-sm font-black text-white disabled:opacity-50">{saving?"در حال ذخیره...":editingId?"ذخیره تغییرات":"ثبت کارمند"}</button>}</div></form></section>
        <section className="min-w-0 rounded-3xl border border-slate-200 bg-white p-3 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-black">فهرست کارکنان</h2><p className="mt-1 text-xs text-slate-500">{activeCompany?.name||"شرکت انتخاب نشده"}</p></div><div className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{filtered.length.toLocaleString("fa-IR")} نفر</div></div>{loading?<div className="grid gap-3 sm:grid-cols-2"><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>:!activeCompanyId?<EmptyState title="شرکت را انتخاب کنید" text="برای مشاهده کارکنان، شرکت فعال را انتخاب کنید."/>:filtered.length===0?<EmptyState title={search?"نتیجه‌ای پیدا نشد":"هنوز کارمندی ثبت نشده"} text={search?"عبارت جستجو را تغییر دهید.":"از فرم افزودن یا Excel استفاده کنید."}/>:<div className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-3">{filtered.map((e)=><EmployeeCard key={e.id} employee={e} onEdit={editEmployee} onPassword={(x)=>{setPasswordEmployee(x);setNewPassword("")}} onRecovery={(x)=>setRecoveryEmployee(x)} onDelete={(x)=>{setDeleteEmployee(x);setDeleteArmed(false)}}/>)}</div>}</section>
      </div>
    </div>
    {passwordEmployee&&<Modal title="رمز فیش حقوقی" onClose={()=>{setPasswordEmployee(null);setNewPassword("")}}><div className="space-y-4"><div className="rounded-2xl bg-indigo-50 p-4"><div className="font-black text-indigo-900">{passwordEmployee.full_name}</div><div className="mt-1 text-xs text-indigo-700">کد پرسنلی: {passwordEmployee.personnel_code}</div></div><input autoFocus type="password" value={newPassword} onChange={(e)=>setNewPassword(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm" placeholder="حداقل ۴ کاراکتر"/><button type="button" onClick={setPassword} disabled={savingPassword} className="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{savingPassword?"در حال ذخیره...":"ذخیره رمز"}</button></div></Modal>}
    {recoveryEmployee&&<Modal title="بازیابی رمز پرسنل" onClose={()=>setRecoveryEmployee(null)}><EmployeeRecoveryPanel employee={recoveryEmployee} companyName={activeCompany?.name} onDone={(updated)=>setEmployees((list)=>list.map((x)=>x.id===updated.id?{...x,...updated}:x))}/></Modal>}
    {deleteEmployee&&<Modal title="حذف دائمی کارمند" onClose={()=>{setDeleteEmployee(null);setDeleteArmed(false)}}><div className="space-y-4"><div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 font-black text-rose-800">{deleteEmployee.full_name}</div><p className="text-sm leading-7 text-slate-600">این عملیات دائمی است و اطلاعات حقوقی وابسته نیز حذف می‌شود.</p><label className="flex gap-3 rounded-xl bg-slate-50 p-3 text-xs font-bold"><input type="checkbox" checked={deleteArmed} onChange={(e)=>setDeleteArmed(e.target.checked)}/>متوجه هستم که حذف دائمی است.</label><button type="button" onClick={deleteEmployeeNow} disabled={!deleteArmed||deleting} className="w-full rounded-xl bg-rose-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40">{deleting?"در حال حذف...":"تأیید نهایی حذف"}</button></div></Modal>}
  </main>;
}
function Stat({label,value}){return <div className="rounded-2xl border border-white/15 bg-white/10 px-3 py-2 text-center"><div className="text-[10px] font-bold text-indigo-100">{label}</div><div className="mt-0.5 text-lg font-black">{Number(value||0).toLocaleString("fa-IR")}</div></div>}
function EmployeeCard({employee,onEdit,onPassword,onRecovery,onDelete}){const has=Boolean(employee.payslip_password||employee.has_payslip_password);return <article className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4 transition hover:border-indigo-200 hover:bg-white hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-base font-black">{employee.full_name||"بدون نام"}</h3><div className="mt-1 flex flex-wrap gap-1.5 text-[11px] font-bold text-slate-500"><span className="rounded-full bg-white px-2 py-1">پرسنلی {employee.personnel_code||"—"}</span><span className="rounded-full bg-white px-2 py-1">ملی {employee.national_id||"—"}</span></div></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-black ${has?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{has?"رمز فعال":"بدون رمز"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Info label="واحد" value={employee.department}/><Info label="سمت" value={employee.job_title||employee.job_group}/><Info label="ایمیل" value={employee.email}/><Info label="حساب" value={employee.bank_account}/></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><button type="button" onClick={()=>onEdit(employee)} className="rounded-xl bg-indigo-50 px-2 py-2.5 text-xs font-black text-indigo-700">ویرایش</button><button type="button" onClick={()=>onPassword(employee)} className="rounded-xl bg-slate-900 px-2 py-2.5 text-xs font-black text-white">{has?"تغییر رمز":"تعیین رمز"}</button><button type="button" onClick={()=>onRecovery(employee)} className="rounded-xl bg-emerald-50 px-2 py-2.5 text-xs font-black text-emerald-700">📩 بازیابی رمز</button><button type="button" onClick={()=>onDelete(employee)} className="rounded-xl bg-rose-50 px-2 py-2.5 text-xs font-black text-rose-700">حذف</button></div></article>}
function Info({label,value}){return <div className="min-w-0 rounded-xl bg-white p-2.5"><div className="text-[10px] font-bold text-slate-400">{label}</div><div className="mt-1 truncate text-xs font-black text-slate-700">{value||"—"}</div></div>}
function Skeleton(){return <div className="h-48 animate-pulse rounded-2xl bg-slate-100"/>}
function EmptyState({title,text}){return <div className="flex min-h-64 items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><div><div className="text-base font-black text-slate-700">{title}</div><p className="mt-2 max-w-md text-xs leading-6 text-slate-500">{text}</p></div></div>}
function Modal({title,children,onClose}){return <div className="fixed inset-0 z-[90] flex items-end justify-center bg-slate-950/60 p-3 backdrop-blur-sm sm:items-center"><div className="w-full max-w-md rounded-3xl bg-white p-5 shadow-2xl sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-lg font-black">{title}</h2><button type="button" onClick={onClose} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-black text-slate-600">×</button></div>{children}</div></div>}
